// <auto-generated />
using System;
using DEGREE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FCUnirea.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241126112233_CreateFCUNIREAComplete")]
    partial class CreateFCUNIREAComplete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FCUnirea.Entities.Comments", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("news_id")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FCUnirea.Entities.Competitions", b =>
                {
                    b.Property<int>("competition_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("competition_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("competition_type")
                        .HasColumnType("int");

                    b.HasKey("competition_id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("FCUnirea.Entities.Feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<string>("review")
                        .HasColumnType("TEXT");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.HasKey("feedback_id");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("FCUnirea.Entities.Games", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("away_team_id")
                        .HasColumnType("int");

                    b.Property<int>("away_team_score")
                        .HasColumnType("int");

                    b.Property<int>("competition_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("game_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("home_team_id")
                        .HasColumnType("int");

                    b.Property<int>("home_team_score")
                        .HasColumnType("int");

                    b.Property<int>("stadium_id")
                        .HasColumnType("int");

                    b.Property<int>("tickets_sold")
                        .HasColumnType("int");

                    b.HasKey("game_id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FCUnirea.Entities.News", b =>
                {
                    b.Property<int>("news_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("news_id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("FCUnirea.Entities.PlayerStatisticsPerCompetiton", b =>
                {
                    b.Property<int>("statistic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("assists")
                        .HasColumnType("int");

                    b.Property<int>("competition_id")
                        .HasColumnType("int");

                    b.Property<int>("goals")
                        .HasColumnType("int");

                    b.Property<int>("minutes_played")
                        .HasColumnType("int");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<int>("red_cards")
                        .HasColumnType("int");

                    b.Property<int>("saves")
                        .HasColumnType("int");

                    b.Property<int>("yellow_cards")
                        .HasColumnType("int");

                    b.HasKey("statistic_id");

                    b.ToTable("PlayerStatisticsPerCompetiton");
                });

            modelBuilder.Entity("FCUnirea.Entities.PlayerStatisticsPerGame", b =>
                {
                    b.Property<int>("statistic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("assists")
                        .HasColumnType("int");

                    b.Property<int>("game_id")
                        .HasColumnType("int");

                    b.Property<int>("goals")
                        .HasColumnType("int");

                    b.Property<int>("minutes_played")
                        .HasColumnType("int");

                    b.Property<int>("passes_completed")
                        .HasColumnType("int");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<int>("red_cards")
                        .HasColumnType("int");

                    b.Property<int>("saves")
                        .HasColumnType("int");

                    b.Property<int>("yellow_cards")
                        .HasColumnType("int");

                    b.HasKey("statistic_id");

                    b.ToTable("PlayerStatisticsPerGame");
                });

            modelBuilder.Entity("FCUnirea.Entities.Players", b =>
                {
                    b.Property<int>("player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("player_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("position")
                        .HasColumnType("int");

                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("player_id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FCUnirea.Entities.Seats", b =>
                {
                    b.Property<int>("seat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("reserved")
                        .HasColumnType("bit");

                    b.Property<string>("seat_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seat_price")
                        .HasColumnType("int");

                    b.Property<int>("seat_type")
                        .HasColumnType("int");

                    b.HasKey("seat_id");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("FCUnirea.Entities.Stadiums", b =>
                {
                    b.Property<int>("stadium_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<int>("seat_id")
                        .HasColumnType("int");

                    b.Property<string>("stadium_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stadium_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("stadium_id");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("FCUnirea.Entities.TeamStatistics", b =>
                {
                    b.Property<int>("statistic_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("competition_id")
                        .HasColumnType("int");

                    b.Property<int>("games_played")
                        .HasColumnType("int");

                    b.Property<int>("goals_conceded")
                        .HasColumnType("int");

                    b.Property<int>("goals_scored")
                        .HasColumnType("int");

                    b.Property<int>("team_id")
                        .HasColumnType("int");

                    b.Property<int>("total_draws")
                        .HasColumnType("int");

                    b.Property<int>("total_losses")
                        .HasColumnType("int");

                    b.Property<int>("total_points")
                        .HasColumnType("int");

                    b.Property<int>("total_wins")
                        .HasColumnType("int");

                    b.HasKey("statistic_id");

                    b.ToTable("TeamStatistics");
                });

            modelBuilder.Entity("FCUnirea.Entities.Teams", b =>
                {
                    b.Property<int>("team_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("is_internal")
                        .HasColumnType("bit");

                    b.Property<string>("record")
                        .HasColumnType("TEXT");

                    b.Property<string>("team_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("team_type")
                        .HasColumnType("int");

                    b.HasKey("team_id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FCUnirea.Entities.Tickets", b =>
                {
                    b.Property<int>("ticket_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date_reservation")
                        .HasColumnType("datetime2");

                    b.Property<int>("game_id")
                        .HasColumnType("int");

                    b.Property<int>("seat_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("ticket_id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("FCUnirea.Entities.Users", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phone_number")
                        .HasColumnType("int");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
